[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.31.0"
allow-dirty = ["ci"]
ci = "github"
installers = ["shell", "homebrew"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
]
install-path = "~/.local/bin"
hosting = "github"
publish-prereleases = false
install-updater = false
